export const UPDATE_STATE = 'UPDATE_STATE';
export const UPDATE_PLAYER_DATA = 'UPDATE_PLAYER_DATA';
export const UPDATE_SESSION_ID = 'UPDATE_SESSION_ID';
export const UPDATE_SNAPSHOTS = 'UPDATE_SNAPSHOTS';
